---
#
# Ansible managed
#
repository:
  description: Install and configure artifactory on your system.
  homepage: https://buluma.github.io/
  topics: artifactory, server, system, ansible, molecule, tox, playbook
